# Generated by Django 3.1.4 on 2021-02-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_shippingaddress_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
