version: '3.7'
volumes:
  pgdata:
services:
  python:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes: 
      - ./amdtelecom:/amdtelecom
    ports: 
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: ./.env

