version: '3.7'
volumes:
  pgdata:
  static_files:
  media_files:
services:
  python:
    build:
      context: .
      dockerfile: docker/prod/python/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=amdtelecom.settings.prod
    volumes: 
      - ./amdtelecom:/amdtelecom
      - static_files:/static_files
      - ./media/:/media/
    ports: 
      - "8000:8000"
    command: gunicorn -w 4 amdtelecom.wsgi -b 0.0.0.0:8000
  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: ./.env
  nginx:
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    volumes:
      - ./amdtelecom:/amdtelecom
      - static_files:/static_files
      - ../amdtelecom/media/:/media/
    ports:
      - 80:80

