# Generated by Django 3.1.4 on 2021-02-17 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Title')),
                ('image', models.ImageField(blank=True, upload_to='categories_images', verbose_name='Image')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=110, unique=True, verbose_name='Slug')),
                ('is_main', models.BooleanField(default=False, verbose_name='is_main')),
                ('is_second', models.BooleanField(default=False, verbose_name='is_second')),
                ('is_third', models.BooleanField(default=False, verbose_name='is_third')),
                ('status', models.BooleanField(default=True, verbose_name='is_active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
                'ordering': ('-created_at', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Title')),
                ('image', models.ImageField(blank=True, upload_to='marka_images', verbose_name='Image')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=110, unique=True, verbose_name='Slug')),
                ('status', models.BooleanField(default=True, verbose_name='is_active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Markas',
                'db_table': 'marka',
                'ordering': ('-created_at', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color Name')),
                ('color_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color code')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True, verbose_name='Slug')),
                ('sku', models.CharField(db_index=True, max_length=50, verbose_name='SKU')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('sale_count', models.IntegerField(default=0, verbose_name='Sale Count')),
                ('is_new', models.BooleanField(default=True, verbose_name='is_new')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is_featured')),
                ('is_discount', models.BooleanField(default=False, verbose_name='is_discount')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price')),
                ('discount_type', models.PositiveIntegerField(choices=[(1, 'Not'), (2, 'Percent'), (3, 'Unit')], default=1, verbose_name='Discount Type')),
                ('discount_value', models.IntegerField(blank=True, null=True, verbose_name='Discount Value')),
                ('status', models.BooleanField(default=True, verbose_name='is_active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='product.category')),
                ('same_product', models.ManyToManyField(blank=True, related_name='_product_same_product_+', to='product.Product')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
                'ordering': ('-created_at', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Title')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tag',
                'ordering': ('-created_at', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Product_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images', verbose_name='Image')),
                ('is_main', models.BooleanField(default=False, verbose_name='Main Image')),
                ('is_second_main', models.BooleanField(default=False, verbose_name='Second Main Image')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'image',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('video', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('external_storage', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('production_year', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('sim_count', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('sim_type', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('operation_system', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('operation_system_version', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('screen_size', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('resolution', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('back_camera', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('front_camera', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('battery', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('weigth', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('prosessor', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('security', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('guarantee', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('operator_prefix', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('wifi', models.BooleanField(blank=True, default=None, null=True)),
                ('allow_3G', models.BooleanField(blank=True, default=None, null=True)),
                ('allow_4G', models.BooleanField(blank=True, default=None, null=True)),
                ('nfc', models.BooleanField(blank=True, default=None, null=True)),
                ('gps', models.BooleanField(blank=True, default=None, null=True)),
                ('eye_recognition', models.BooleanField(blank=True, default=None, null=True)),
                ('waterproof', models.BooleanField(blank=True, default=None, null=True)),
                ('faceID', models.BooleanField(blank=True, default=None, null=True)),
                ('shockproof', models.BooleanField(blank=True, default=None, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='product.product')),
            ],
            options={
                'verbose_name': 'Product_color',
                'verbose_name_plural': 'Product_colors',
                'db_table': 'product_colors',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='products', to='product.Tag'),
        ),
        migrations.AddField(
            model_name='product',
            name='who_like',
            field=models.ManyToManyField(blank=True, related_name='liked_products', to='account.Customer'),
        ),
        migrations.AddField(
            model_name='category',
            name='marka',
            field=models.ManyToManyField(related_name='categories', to='product.Marka'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='_category_parent_+', to='product.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('title', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('slug',)},
        ),
    ]
