# Generated by Django 3.1.4 on 2021-02-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210218_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=110, unique=True, verbose_name='Slug'),
        ),
    ]
