# Generated by Django 3.1.4 on 2021-02-19 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_delete_product_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Detail',
                'verbose_name_plural': 'Details',
                'db_table': 'detail',
            },
        ),
        migrations.CreateModel(
            name='Product_detail_rel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_detail_rel', to='product.detail')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_detail_rel', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Detail_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_name', to='product.category')),
            ],
            options={
                'verbose_name': 'Detail Name',
                'verbose_name_plural': 'Detail Names',
                'db_table': 'detail_name',
            },
        ),
        migrations.AddField(
            model_name='detail',
            name='detail_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='product.detail_name'),
        ),
    ]
