# Generated by Django 3.1.4 on 2021-02-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210219_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail_name',
            name='category',
        ),
        migrations.AddField(
            model_name='detail_name',
            name='category',
            field=models.ManyToManyField(related_name='detail_name', to='product.Category'),
        ),
    ]
