# Generated by Django 3.1.4 on 2021-02-20 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_detail_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='value',
            field=models.CharField(max_length=50, verbose_name='Value'),
        ),
        migrations.CreateModel(
            name='Detail_value_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_detail_name', to='product.detail_name')),
                ('detail_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_detail_value', to='product.detail')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_detail', to='product.product')),
            ],
        ),
    ]
